// app/layout.tsx
import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google"; //font ใน figma
import Navbar from './navbar';
import './globals.css';
import { BookingProvider } from "./context/bookingcontext";

const inter = Inter({  //font ใน figma ยังไม่บันทึก
  subsets: ["latin"],
  weight: ["400", "700"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "ClubcarsRental",
  description: "Generated by clubcars",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
       <BookingProvider>
        <Navbar /> {/* Navbar จะแสดงทุกหน้า */}
        <main className="container mx-auto p-4">{children}</main>
        </BookingProvider>
      </body>
    </html>
  );
}
